eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: demo
          uri: lb://DEMO-SERVICE
          predicates:
            - Path=/demo-service/**
